INSERT INTO AUTOR (NOME) VALUES ('Manoel Bandeira');
INSERT INTO AUTOR (NOME) VALUES ('Gracilianos Ramos');

INSERT INTO  LIVRO ( ID, TITULO, QUANTIDADE ) VALUES ( 1, 'Use a cabeça Java', 30 );
INSERT INTO  LIVRO ( ID, TITULO, QUANTIDADE ) VALUES ( 2, 'Java como programar', 50 );
INSERT INTO  LIVRO ( ID, TITULO, QUANTIDADE ) VALUES ( 3, 'Spring boot', 20 );